import React from 'react';
import { FaEnvelopeOpenText } from 'react-icons/fa';

// import Head from 'next/head';
// import Image from 'next/image';
// import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className='tw-bg-main-background tw-min-h-screen'>
      <div className='tw-max-w-screen-lg tw-my-0 tw-mx-auto'>
        <div className='tw-font-open-sans'>
          <div className='tw-flex tw-items-center tw-uppercase tw-text-center tw-tracking-widest tw-w-9/12 tw-my-0 tw-mx-auto'>
            <div className='tw-w-1/3'>
              <div className='tw-text-3xl'>Jepi</div>
              <div>Usuluddin</div>
            </div>
            <div className='tw-w-1/3 tw-border-t tw-border-black tw-px-4' />
            <div className='tw-w-1/3'>
              <div className='tw-text-3xl'>Reza</div>
              <div>Ayu Pertiwi</div>
            </div>
          </div>

          <div className='tw-w-1/2 tw-my-12 tw-mx-auto tw-flex tw-items-center'>
            <div className='tw-w-full tw-border-t tw-border-black' />
            <div className='tw-w-1/3 tw-flex tw-justify-center tw-text-gray'>
              <FaEnvelopeOpenText className='tw-fill-current tw-text-gray-600' />
            </div>
            <div className='tw-w-full tw-border-t tw-border-black' />
          </div>

          <div className='tw-w-9/12 tw-mx-auto tw-my-0 tw-text-center'>
            <div>
              Kepada Yth.
              <br />
              Bapak/Ibu/Saudra/i
            </div>
            <div className='tw-font-sacramento tw-text-5xl tw-my-4 tw-font-bold'>
              Nama Tamu Undangan
            </div>
            <div>Di tempat.</div>
          </div>

          <div className='tw-w-1/2 tw-my-12 tw-mx-auto tw-border-t tw-border-black' />
        </div>
      </div>
    </div>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name='description' content='Generated by create next app' />
    //     <link rel='icon' href='/favicon.ico' />
    //   </Head>

  //   <main className={styles.main}>
  //     <h1 className={styles.title}>
  //       Welcome to
  //       <a href='https://nextjs.org'>Next.js!</a>
  //     </h1>

  //     <p className={styles.description}>
  //       Get started by editing
  //       {' '}
  //       <code className={styles.code}>pages/index.js</code>
  //     </p>

  //     <div className={styles.grid}>
  //       <a href='https://nextjs.org/docs' className={styles.card}>
  //         <h2>Documentation &rarr;</h2>
  //         <p>Find in-depth information about Next.js features and API.</p>
  //       </a>

  //       <a href='https://nextjs.org/learn' className={styles.card}>
  //         <h2>Learn &rarr;</h2>
  //         <p>Learn about Next.js in an interactive course with quizzes!</p>
  //       </a>

  //       <a
  //         href='https://github.com/vercel/next.js/tree/master/examples'
  //         className={styles.card}
  //       >
  //         <h2>Examples &rarr;</h2>
  //         <p>Discover and deploy boilerplate example Next.js projects.</p>
  //       </a>

  //       <a
  //         href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
  //         className={styles.card}
  //       >
  //         <h2>Deploy &rarr;</h2>
  //         <p>
  //           Instantly deploy your Next.js site to a public URL with Vercel.
  //         </p>
  //       </a>
  //     </div>
  //   </main>

  //   <footer className={styles.footer}>
  //     <a
  //       href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
  //       target='_blank'
  //       rel='noopener noreferrer'
  //     >
  //       Powered by
  //       {' '}
  //       <span className={styles.logo}>
  //         <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
  //       </span>
  //     </a>
  //   </footer>
  // </div>
  );
}
